### ISSUE TITLE
Corrupted or pink screen on some Android devices after usage of plugin

### ISSUE THREAD

**Issue by MyOwnClone** [Over17/UnityAndroidPermissions#10]
Hi, at first I want to thank for the plugin and the great work, but I have run to some problems on our project and I am not sure if it's the plugin's fault, my fault, Unity's, Android OS's or some race condition.

I have used the plugin the way it is used in the example project, adapted it in fair standart way in our project. I called the plugin in the first scene of the project after starting the game. On development Android device, everything runs fine, it detects whether the permission is granted and it asks for it if it is not. We are using Unity 5.6.5p3 for the development. The device I developed with is Samsung Galaxy S6 Edge, running on Android 6.

After deploying the build to broader audience, reports started to appear of corrupted textures, whole screen in the first scene pink and so. It seems it affects the UI in particular, everything with textures where is alpha channel. Regular game geometry is OK. On some devices and in certain cases, screen is not pink, but it looks like "hall of mirrors" bug. Basically normal UI framebuffer tiled i.e. in 10x4 matrix.

I think something in this plugin, or the way it is used, corrupts the memory, framebuffer, or the way how Unity works. I know this is very strange as everything it does is running managed code and calling Java. There is maybe some native bridge, but all code in this plugin is managed, either in C# or in Java. So what can corrupt the memory and textures?

It seems (I am not sure of it) that somehow just the presence of the plugin (even before any call to it) somehow corrupts the run of the Unity player from the beginning. Please note that this does not happen on all the devices. I'd say that this happens on 1/10 of the tested devices. I will attach the list of the devices on which it occurs.

Also, this happens when OBB is present. We are able to get to the later scenes, even to main game which certainly uses assets that are in OBB. It is maybe somehow connected to the fact that this happens more often when game is installed from Google Play Store. When we deploy the game via ADB, this happens in almost none of the cases.

What follows is a list of devices, it consist of manufacturer, device, Android version, device code and SoC.

```
Samsung | Galaxy On5 LTE | 6.0.1 | SM-S550TL | Samsung Exynos 3 Quad 3475
Samsung | Galaxy A3 2016 | 6.0.1 | SM-A310F | Samsung Exynos 7   Quad 7578
LG | Nexus 5 | 6 | D821 | Qualcomm   Snapdragon 800
Samsung | Galaxy J7 Pro | 7 | SM-L730F/DS | Exynos 7870 Octa
Huawei | P9 | 6 | EVA-L09 | HiSilicon Kirin   955
Samsung | Galaxy S6 Edge+ | 7 | SM-G928F | Exynos 7420
Samsung | Galaxy S7 Edge | 7 | SM-G935F | Exynos 8890 Octa
Samsung | Galaxy Tab S2   9.7 | 7 | SM-T810 | Exynos 5433
Huawei | Mate 9 | 7 | MHA-L29 | HiSilicon Honor   KIRIN960 Hi3660
ASUS | ZenPad 3S 10 | 6 | P027 / Z500M | MediaTek MT8176
```

Do you know what can cause the corrupted screen? Or how to solve it? Is it Unity's issue, plugin issue or ours?

**Comment by Over17** [comment]
Hi!

I think what you are observing is: https://forum.unity.com/threads/apk-with-expansion-file-obb-fails-to-load-the-second-scene-until-the-phone-has-been-restarted.465714/

The thread has quite comprehensive analysis of what's going on.

Your behavior is most likely because of the app not being able to access the OBB. The scene is becoming pink because of shaders missing; why did they end up in the OBB - that's another question - more details available here https://docs.unity3d.com/Manual/android-OBBsupport.html

The OBB is being mounted very early (before the engine is initialized), so the plugin is unable ask the user for the permission _before_ the OBB has to be loaded.

The OBB is also mounted in onResume().

So, there's nothing with the plugin which corrupts your game. :)

Possible solutions:
- get rid of the OBB. The most radical and the best solution. Try utilizing asset bundles instead.
- ask for READ_EXTERNAL_STORAGE permission as soon as possible, and make Unity somehow pause and resume (show another activity? for a second) - it should make OBB loaded and fix all your issues.

Hope that helps.
Yury

**Comment by MyOwnClone** [comment]
Hi, thanks for the response,

> I think what you are observing is: https://forum.unity.com/threads/apk-with-expansion-file-obb-fails-to-load-the-second-scene-until-the-phone-has-been-restarted.465714/

I think this is not the case, because our second scene actually loads and we are able to get even to any other scene, which is in OBB. We are able to get past menus to the actual game, where all the non-alpha assets are visible and game runs. Just the alpha based assets and UI is pink/corrupted.

As for possible solutions:
- I am told that getting rid of the OBB is not option for us, as the asset bundles would be much more work and time for us, which we do not have
- ask for READ_EXTERNAL_STORAGE - how do you mean it? We have it in our manifest, so you mean asking for the permission via the plugin? And than, after granting, doing pause and resume? 

Thanks a lot,
Tom

**Comment by Over17** [comment]
Okay let's put it this way then:
- in Unity Editor, **disable** "Split Application Binary", Build&Run - does it work?
- in Unity Editor, **enable** "Split Application Binary", Build&Run - does it work?
- install the game to an affected device from Google Play - does it work?
-- if it doesn't, restart the device completely and run the game again - does it work?

Is there anything in the logcat when the game is not working correctly?

**Comment by MyOwnClone** [comment]
OK, it seems that we have solved it. Or _"solved"_ it, I should say. In friday, I've made an experimental version without usage of the plugin for getting and setting the rights and handling our use case differently. But back then, we had to push it to our testers that are located off site, so in the mean time, I have reported the issue here. 

We've just got report from our testers, that by removing the usage of the plugin, we've got rid of the pink/corrupted screen issue completely.

So, this seems to be related to the plugin somehow, as by simply removing it, the issue goes away. And the original issue, that the plugin should solve, we've resolved differently - by trying to load scene that should be on OBB and if it fails, asking user to allow the permission manually and restart the app.

Our case is (maybe) solved, but this does not solve the plugin issue itself.

As for the suggestion about **restart**, you've mentioned: no, restart did not help in any of the case. Only upgrade of Android OS. Also, we've had two devices - both Galaxy S6 edge model, one with Android 6 and one with 7. Problem occured when getting from Google Play on the 6 OS device, but not on the 7 OS device...

As for the rest of the suggestions, I haven't tried the "**Split binary**" option yet, but if you insist on that and if it would help you in development/bugfixing, I can try that too even when our case is somehow solved.

**Comment by Over17** [comment]
I'm happy that it work for you - too bad you are still thinking it's the plugin. I'm quite sure it's not the plugin causing the issue, rather it's a missing permission, most likely the READ_EXTERNAL_STORAGE. Maybe it's being asked too late. Unfortunately the details you posted here are not enough to find the root cause of the issue.

The "Split application binary" option is "enable/disable the OBB".

**Comment by MyOwnClone** [comment]
I am not saying that it is the plugin and I am blaming no one:-) It just occured to me as the most plausible explanation. It would be strange if managed code plugin caused this and broke the engine so badly, so if you're saying it is not the case, I believe you.

As for the `READ_EXTERNAL_STORAGE`, we have it in the manifest and had it there all the time... so I presume you mean we should ask for it via the plugin? And should we ask for the `WRITE_EXTERNAL_STORAGE` too? Because we have asked for `WRITE_EXTERNAL_STORAGE` and by using the plugin to ask for it, it has caused us the pink screen issue in the first place...

**Comment by Over17** [comment]
Let me try to explain it.

You have READ_EXTERNAL_STORAGE in the manifest.

Without the plugin, Unity asks for all the permissions on very first startup, early before the engine is initialized. If the user grants the permission, everything works fine.

With the plugin, a special flag is added to the manifest to suppress this dialog. Instead, you have to call an API to request a permission. Unfortunately, you can call into this API only after the engine is initialized; at this point the OBB had already been mounted, or not failed to mount because of a missing permission. The OBB mount failure usually happens on buggy devices when installing from Google Play, or devices prior to API 19 (Android 4.4).

The few ways known to me to workaround the OBB mount failure because of a missing permission are restarting the device, or pausing/resuming the activity AFTER the user has clicked "accept" in the permission dialog.

The issue is not present when you install the OBB by doing "build&run" in the Unity Editor, or when the OBB is disabled ("Split application binary" turned off).

It could be that you are facing a completely different issue; however, I haven't heard anything like that yet. In that case, if you could at least share your logcat (development version preferred) - would be helpful.

**Comment by MyOwnClone** [comment]
Hi, thanks again for clarification, much appreciated...

As for your answers:

> Unfortunately, you can call into this API only after the engine is initialized; at this point the OBB had already been mounted, or not failed to mount because of a missing permission.

This is the thing I do not understand, because our testers reported that they were able to get into game and into all the other scenes. But all the alpha textures and UI were wrong. Maybe the reports are wrong.

> pausing/resuming the activity AFTER the user has clicked "accept" in the permission dialog.

Ok, this is valuable insight. So if I understand correctly, Unity will try to mount the OBB again in this case?

> The issue is not present when you install the OBB by doing "build&run" in the Unity Editor, or when the OBB is disabled ("Split application binary" turned off).

Yes, this is true.

As for the logcat output, I will try to tell our testers to get it from affected device...

**Comment by Over17** [comment]
> Ok, this is valuable insight. So if I understand correctly, Unity will try to mount the OBB again in this case?
Correct.

> This is the thing I do not understand, because our testers reported that they were able to get into game and into all the other scenes. But all the alpha textures and UI were wrong. Maybe the reports are wrong.
Yes this sounds a bit weird - logcat is much appreciated.

**Comment by Over17** [comment]
No updates.

**Comment by fdoumhan** [comment]
> Hi!
> 
> I think what you are observing is: https://forum.unity.com/threads/apk-with-expansion-file-obb-fails-to-load-the-second-scene-until-the-phone-has-been-restarted.465714/
> 
> The thread has quite comprehensive analysis of what's going on.
> 
> Your behavior is most likely because of the app not being able to access the OBB. The scene is becoming pink because of shaders missing; why did they end up in the OBB - that's another question - more details available here https://docs.unity3d.com/Manual/android-OBBsupport.html
> 
> The OBB is being mounted very early (before the engine is initialized), so the plugin is unable ask the user for the permission _before_ the OBB has to be loaded.
> 
> The OBB is also mounted in onResume().
> 
> So, there's nothing with the plugin which corrupts your game. :)
> 
> Possible solutions:
> 
> * get rid of the OBB. The most radical and the best solution. Try utilizing asset bundles instead.
> * ask for READ_EXTERNAL_STORAGE permission as soon as possible, and make Unity somehow pause and resume (show another activity? for a second) - it should make OBB loaded and fix all your issues.
> 
> Hope that helps.
> Yury

I want to try the solution pause/resume unity activity.
Fo pausing, I use
 activity.Call<bool>("moveTaskToBack", true);
But of course, another activity should be shown. I stuck here. How can I switch the activity for a while?
I know this is an irrelevant question with your plugin, but I searched a lot and found nothing. just need some help.

**Comment by Over17** [comment]
@fdoumhan I was thinking of the following:
- implement an empty activity which quits in onResume() or something like that
- in Unity activity, somewhere before the OBB is mounted, start this empty activity
