### ISSUE TITLE
Support for the Android M "Don't show again" checkbox

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Over17/UnityAndroidPermissions#14]
Would be great to be able toprocess the case when in Andoird M+ uses ticked the "Don't show again" checkbox at the permission request popup.

Looks like ActivityCompat.shouldShowRequestPermissionRationale can help here.

**Comment by Over17** [comment]
This is an Android OS feature.

If the user denies a prompt once, and the app shows same permission dialog again - the OS will add "Don't show again" checkbox automatically. If the user selects the checkbox, all subsequent attempts to show the dialog will return "denied" without actually showing the dialog.

The shouldShowRequestPermissionRationale() function returns true after the user has denied the permission once, so that the developer can show an explanation WHY the user should allow this permissions. If the user has selected "Don't show again", shouldShowRequestPermissionRationale() returns false.

Adding rationale to the plugin may be a good idea. However it must be
- customizable
- localizable
Based on that, I've left the rationale magic to the developer himself.

Hope that explains things.

**Comment by DmitriyYukhanov** [comment]
Thanks, yes, fair enough.
