### ISSUE TITLE
Not working for development builds

### ISSUE THREAD

**Issue by JackM36** [Over17/UnityAndroidPermissions#18]
I have implemented this plugin in my app and it works as expected.

However, if I make a development build (from Unity build settings) of the same app, it will always automatically return Denied. The permission window does not appear at all.

Any ideas how to resolve this issue?

**Comment by Over17** [comment]
Hi!

Never heard of such thing before.
- what is the permission in question?
- what are you calling and how do you get the result?
- do you completely remove the app or install it on top of the non-dev version?
- is there a logcat of the dev build you can share?

**Comment by Over17** [comment]
I think there are two reasons for the RequestPermission to return immediately with a result of "denied":
1. The user has tapped "deny" and selected "don't ask again"
2. The permission is not declared in the manifest.

Since 1 is not your case, could you check 2? However I'd expect it to be vice versa - dev build adds read_external_storage automatically, while you need to add it manually for release builds.

**Comment by JackM36** [comment]
I will check and let you know

**Comment by JackM36** [comment]
I removed the permission tests, and my app is crashing (due to not having permissions to read data for example) in dev build. Therefore I don't think the dev build adds permissions on its own.

Is there maybe a way for the plugin to not enable `SkipPermissionsDialog`, without changing the plugin itself? Maybe I can use the default dialog just for the dev build.

**Comment by Over17** [comment]
Unfortunately there isn't. If `skipPermissionsDialog` is not set, then all the permissions are being prompted at the very first start, so there's little point in having any subsequent prompts (apart from if the user has denied the request).
